apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-02T05:58:47Z"
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.2
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    release: monitoring-operator
  name: prometheus-operator-monitoring-operator
  namespace: cattle-prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-operator
      chart: prometheus-operator-0.0.2
      release: monitoring-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-operator
        chart: prometheus-operator-0.0.2
        release: monitoring-operator
    spec:
      containers:
      - args:
        - --kubelet-service=cattle-prometheus/expose-kubelets-metrics
        - --log-format=logfmt
        - --log-level=info
        - --prometheus-config-reloader=rancher/coreos-prometheus-config-reloader:v0.32.0
        - --config-reloader-image=rancher/coreos-configmap-reload:v0.0.1
        - --labels=monitoring.coreos.com=true
        - --crd-apigroup=monitoring.coreos.com
        - --manage-crds=false
        - --with-validation=true
        image: rancher/coreos-prometheus-operator:v0.32.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-operator-monitoring-operator
      serviceAccountName: prometheus-operator-monitoring-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
