apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  generateName: exporter-kube-state-cluster-monitoring-5bc6dff69b-
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.0.1
    pod-template-hash: 5bc6dff69b
    release: cluster-monitoring
  name: exporter-kube-state-cluster-monitoring-5bc6dff69b-k9cbc
  namespace: cattle-prometheus
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: exporter-kube-state-cluster-monitoring-5bc6dff69b
    uid: 4f897d8a-46a1-4bad-8c0f-86503349646e
spec:
  containers:
  - image: rancher/coreos-kube-state-metrics:v1.8.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 100
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
    name: kube-state
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8081
      name: http-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 130Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: exporter-kube-state-cluster-monitoring-token-m5zdx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: zx
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccount: exporter-kube-state-cluster-monitoring
  serviceAccountName: exporter-kube-state-cluster-monitoring
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: exporter-kube-state-cluster-monitoring-token-m5zdx
    secret:
      defaultMode: 420
      secretName: exporter-kube-state-cluster-monitoring-token-m5zdx
