apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T05:58:47Z"
  labels:
    app: operator-init
    chart: operator-init-0.1.0
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    release: monitoring-operator
  name: operator-init-monitoring-operator
  namespace: cattle-prometheus
secrets:
- name: operator-init-monitoring-operator-token-fgvjp
