apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T05:58:47Z"
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.2
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    release: monitoring-operator
  name: prometheus-operator-monitoring-operator
  namespace: cattle-prometheus
secrets:
- name: prometheus-operator-monitoring-operator-token-fn7rr
