apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:51Z"
  labels:
    monitoring.coreos.com: "true"
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: cattle-prometheus
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: cluster-monitoring
    uid: 4307ec53-11e2-4f64-ae06-282edab58dab
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
