apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: exporter-node
    chart: exporter-node-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    k8s-app: node
    monitoring.coreos.com: "true"
    release: cluster-monitoring
  name: expose-node-metrics
  namespace: cattle-prometheus
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9796
    protocol: TCP
    targetPort: 9796
  selector:
    app: exporter-node
    chart: exporter-node-0.0.1
    release: cluster-monitoring
  sessionAffinity: None
  type: ClusterIP
