apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: operator-init
    chart: operator-init-0.1.0
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
  name: operator-init-cluster-monitoring
  namespace: cattle-prometheus
secrets:
- name: operator-init-cluster-monitoring-token-zpb2g
