apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: exporter-node
    chart: exporter-node-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
  name: exporter-node-cluster-monitoring
  namespace: cattle-prometheus
secrets:
- name: exporter-node-cluster-monitoring-token-ds7f4
