apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:47Z"
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.2
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    monitoring.coreos.com: "true"
    release: monitoring-operator
  name: expose-operator-metrics
  namespace: cattle-prometheus
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 47323
    protocol: TCP
    targetPort: http
  selector:
    app: prometheus-operator
    chart: prometheus-operator-0.0.2
    release: monitoring-operator
  sessionAffinity: None
  type: ClusterIP
