apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    k8s-app: kube-state
    monitoring.coreos.com: "true"
    release: cluster-monitoring
  name: expose-kubernetes-metrics
  namespace: cattle-prometheus
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: exporter-kube-state
    chart: exporter-kube-state-0.0.1
    release: cluster-monitoring
  sessionAffinity: None
  type: ClusterIP
