apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2020-04-02T05:58:51Z"
  labels:
    app: exporter-fluentd
    chart: exporter-fluentd-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
    source: rancher-monitoring
  name: exporter-fluentd-cluster-monitoring
  namespace: cattle-prometheus
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: metric
    relabelings:
    - action: replace
      regex: (.+)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_host_ip
      targetLabel: host_ip
    - action: replace
      regex: (.+)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    scheme: http
  namespaceSelector:
    matchNames:
    - cattle-logging
  selector:
    matchLabels:
      app: fluentd
