apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
  name: cluster-monitoring
  namespace: cattle-prometheus
secrets:
- name: cluster-monitoring-token-wkfxv
