apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: grafana
    chart: grafana-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    monitoring.coreos.com: "true"
    release: cluster-monitoring
  name: expose-grafana-metrics
  namespace: cattle-prometheus
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 3000
    protocol: TCP
    targetPort: web
  selector:
    app: grafana
    chart: grafana-0.0.1
    release: cluster-monitoring
  sessionAffinity: None
  type: ClusterIP
