apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    kubernetes.io/cluster-service: "true"
    release: cluster-monitoring
  name: access-prometheus
  namespace: cattle-prometheus
spec:
  clusterIP: 10.43.181.250
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: nginx-http
  selector:
    app: prometheus
    chart: prometheus-0.0.1
    release: cluster-monitoring
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
