apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  creationTimestamp: "2020-04-02T04:34:07Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  groupPriorityMinimum: 1000
  service: null
  version: v1
  versionPriority: 100
