apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: exporter-node
    chart: exporter-node-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
  name: exporter-node-cluster-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exporter-node-cluster-monitoring
subjects:
- kind: ServiceAccount
  name: exporter-node-cluster-monitoring
  namespace: cattle-prometheus
