apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"proxy-clusterrole-kubeapiserver"},"rules":[{"apiGroups":[""],"resources":["nodes/metrics","nodes/proxy","nodes/stats","nodes/log","nodes/spec"],"verbs":["get","list","watch","create"]}]}
  creationTimestamp: "2020-04-02T04:33:05Z"
  name: proxy-clusterrole-kubeapiserver
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  - nodes/log
  - nodes/spec
  verbs:
  - get
  - list
  - watch
  - create
