apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2020-04-02T04:32:52Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:namespace-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/finalize
  - namespaces/status
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - deletecollection
  - get
  - list
