apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-04-02T05:58:50Z"
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
  name: prometheus-cluster-monitoring-cattle-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-monitoring-cattle-prometheus
subjects:
- kind: ServiceAccount
  name: cluster-monitoring
  namespace: cattle-prometheus
