apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-04-03T01:39:28Z"
  labels:
    app: katafygio
    chart: katafygio-1.0.0
    heritage: Tiller
    io.cattle.field/appId: katafygio
    release: katafygio
  name: katafygio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katafygio
subjects:
- kind: ServiceAccount
  name: katafygio
  namespace: katafygio
