apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-04-02T05:58:47Z"
  labels:
    app: operator-init
    chart: operator-init-0.1.0
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    release: monitoring-operator
  name: operator-init-monitoring-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
  - patch
