apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-04-02T04:34:05Z"
  labels:
    cattle.io/creator: norman
  name: project-member-promoted
rules:
- apiGroups:
  - '*'
  resources:
  - persistentvolumes
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - '*'
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
