apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    authz.cluster.cattle.io/clusterrole-owner: cluster-owner
  creationTimestamp: "2020-04-02T04:34:05Z"
  labels:
    cattle.io/creator: norman
  name: cluster-owner
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
