apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2020-04-02T04:32:52Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:replication-controller
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
