apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-04-03T01:39:28Z"
  labels:
    app: katafygio
    chart: katafygio-1.0.0
    heritage: Tiller
    io.cattle.field/appId: katafygio
    release: katafygio
  name: katafygio
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
