apiVersion: v1
data:
  rke-network-plugin: "\n---\nkind: ClusterRole\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n
    \ name: flannel\nrules:\n  - apiGroups: ['extensions']\n    resources: ['podsecuritypolicies']\n
    \   verbs: ['use']\n    resourceNames: ['psp.flannel.unprivileged']\n  - apiGroups:\n
    \     - \"\"\n    resources:\n      - pods\n    verbs:\n      - get\n  - apiGroups:\n
    \     - \"\"\n    resources:\n      - nodes\n    verbs:\n      - list\n      -
    watch\n  - apiGroups:\n      - \"\"\n    resources:\n      - nodes/status\n    verbs:\n
    \     - patch\n---\nkind: ClusterRoleBinding\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n
    \ name: flannel\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: ClusterRole\n
    \ name: flannel\nsubjects:\n- kind: ServiceAccount\n  name: flannel\n  namespace:
    kube-system\n---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: flannel\n
    \ namespace: kube-system\n\n---\napiVersion: policy/v1beta1\nkind: PodSecurityPolicy\nmetadata:\n
    \ name: psp.flannel.unprivileged\n  annotations:\n    seccomp.security.alpha.kubernetes.io/allowedProfileNames:
    docker/default\n    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default\n
    \   apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default\n
    \   apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default\nspec:\n
    \ privileged: false\n  volumes:\n    - configMap\n    - secret\n    - emptyDir\n
    \   - hostPath\n  allowedHostPaths:\n    - pathPrefix: \"/etc/cni/net.d\"\n    -
    pathPrefix: \"/etc/kube-flannel\"\n    - pathPrefix: \"/run/flannel\"\n  readOnlyRootFilesystem:
    false\n  # Users and groups\n  runAsUser:\n    rule: RunAsAny\n  supplementalGroups:\n
    \   rule: RunAsAny\n  fsGroup:\n    rule: RunAsAny\n  # Privilege Escalation\n
    \ allowPrivilegeEscalation: false\n  defaultAllowPrivilegeEscalation: false\n
    \ # Capabilities\n  allowedCapabilities: ['NET_ADMIN']\n  defaultAddCapabilities:
    []\n  requiredDropCapabilities: []\n  # Host namespaces\n  hostPID: false\n  hostIPC:
    false\n  hostNetwork: true\n  hostPorts:\n  - min: 0\n    max: 65535\n  # SELinux\n
    \ seLinux:\n    # SELinux is unsed in CaaSP\n    rule: 'RunAsAny'\n---\nkind:
    ConfigMap\napiVersion: v1\nmetadata:\n  name: kube-flannel-cfg\n  namespace: kube-system\n
    \ labels:\n    tier: node\n    app: flannel\ndata:\n  cni-conf.json: |\n    {\n
    \     \"name\": \"cbr0\",\n      \"cniVersion\":\"0.3.1\",\n      \"plugins\":
    [\n        {\n          \"type\": \"flannel\",\n          \"delegate\": {\n            \"hairpinMode\":
    true,\n            \"isDefaultGateway\": true\n          }\n        },\n        {\n
    \         \"type\": \"portmap\",\n          \"capabilities\": {\n            \"portMappings\":
    true\n          }\n        }\n      ]\n    }\n  net-conf.json: |\n    {\n      \"Network\":
    \"10.42.0.0/16\",\n      \"Backend\": {\n        \"Type\": \"vxlan\",\n        \"VNI\":
    1,\n        \"Port\": 8472\n      }\n    }\n---\napiVersion: apps/v1\nkind: DaemonSet\nmetadata:\n
    \ name: kube-flannel\n  namespace: kube-system\n  labels:\n    tier: node\n    k8s-app:
    flannel\nspec:\n  selector:\n    matchLabels:\n      k8s-app: flannel\n  template:\n
    \   metadata:\n      labels:\n        tier: node\n        k8s-app: flannel\n    spec:\n
    \     affinity:\n        nodeAffinity:\n          requiredDuringSchedulingIgnoredDuringExecution:\n
    \           nodeSelectorTerms:\n              - matchExpressions:\n                -
    key: beta.kubernetes.io/os\n                  operator: NotIn\n                  values:\n
    \                   - windows\n      hostNetwork: true\n\n      tolerations:\n
    \     - operator: Exists\n      serviceAccountName: flannel\n      \n      containers:\n
    \     - name: kube-flannel\n        image: rancher/coreos-flannel:v0.11.0-rancher1\n
    \       command:\n        - /opt/bin/flanneld\n        args:\n        - --ip-masq\n
    \       - --kube-subnet-mgr\n        resources:\n          requests:\n            cpu:
    \"100m\"\n            memory: \"50Mi\"\n          limits:\n            cpu: \"100m\"\n
    \           memory: \"50Mi\"\n        securityContext:\n          privileged:
    false\n          capabilities:\n             add: [\"NET_ADMIN\"]\n        env:\n
    \       - name: POD_NAME\n          valueFrom:\n            fieldRef:\n              fieldPath:
    metadata.name\n        - name: POD_NAMESPACE\n          valueFrom:\n            fieldRef:\n
    \             fieldPath: metadata.namespace\n        volumeMounts:\n        -
    name: run\n          mountPath: /run\n        - name: cni\n          mountPath:
    /etc/cni/net.d\n        - name: flannel-cfg\n          mountPath: /etc/kube-flannel/\n
    \     - name: install-cni\n        image: rancher/flannel-cni:v0.3.0-rancher5\n
    \       command: [\"/install-cni.sh\"]\n        env:\n        # The CNI network
    config to install on each node.\n        - name: CNI_NETWORK_CONFIG\n          valueFrom:\n
    \           configMapKeyRef:\n              name: kube-flannel-cfg\n              key:
    cni-conf.json\n        - name: CNI_CONF_NAME\n          value: \"10-flannel.conflist\"\n
    \       volumeMounts:\n        - name: cni\n          mountPath: /host/etc/cni/net.d\n
    \       - name: host-cni-bin\n          mountPath: /host/opt/cni/bin/\n      volumes:\n
    \       - name: run\n          hostPath:\n            path: /run\n        - name:
    cni\n          hostPath:\n            path: /etc/cni/net.d\n        - name: flannel-cfg\n
    \         configMap:\n            name: kube-flannel-cfg\n        - name: host-cni-bin\n
    \         hostPath:\n            path: /opt/cni/bin\n  updateStrategy:\n\n    rollingUpdate:\n
    \     maxUnavailable: 1\n    type: RollingUpdate\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T04:33:37Z"
  name: rke-network-plugin
  namespace: kube-system
