apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-04-02T04:33:52Z"
  labels:
    controller-uid: 727b8fe5-2a15-4c86-ba1d-b89d7d0a68d1
    job-name: rke-ingress-controller-deploy-job
  name: rke-ingress-controller-deploy-job
  namespace: kube-system
spec:
  backoffLimit: 10
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 727b8fe5-2a15-4c86-ba1d-b89d7d0a68d1
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 727b8fe5-2a15-4c86-ba1d-b89d7d0a68d1
        job-name: rke-ingress-controller-deploy-job
      name: rke-deploy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
      containers:
      - command:
        - kubectl
        - apply
        - -f
        - /etc/config/rke-ingress-controller.yaml
        image: rancher/hyperkube:v1.17.4-rancher1
        imagePullPolicy: IfNotPresent
        name: rke-ingress-controller-pod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeName: zx
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rke-job-deployer
      serviceAccountName: rke-job-deployer
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: rke-ingress-controller
            path: rke-ingress-controller.yaml
          name: rke-ingress-controller
        name: config-volume
