apiVersion: coordination.k8s.io/v1beta1
kind: Lease
metadata:
  creationTimestamp: "2020-04-02T04:32:55Z"
  name: kube-controller-manager
  namespace: kube-system
spec:
  acquireTime: "2020-04-03T01:36:16.000000Z"
  holderIdentity: zx_7d542e86-d7a5-4df9-aa8e-e93259ee938d
  leaseDurationSeconds: 15
  leaseTransitions: 2
  renewTime: "2020-04-03T02:02:12.996461Z"
