apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-02T04:33:52Z"
  generateName: rke-ingress-controller-deploy-job-
  labels:
    controller-uid: 727b8fe5-2a15-4c86-ba1d-b89d7d0a68d1
    job-name: rke-ingress-controller-deploy-job
  name: rke-ingress-controller-deploy-job-2w9rh
  namespace: kube-system
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: rke-ingress-controller-deploy-job
    uid: 727b8fe5-2a15-4c86-ba1d-b89d7d0a68d1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/os
            operator: NotIn
            values:
            - windows
  containers:
  - command:
    - kubectl
    - apply
    - -f
    - /etc/config/rke-ingress-controller.yaml
    image: rancher/hyperkube:v1.17.4-rancher1
    imagePullPolicy: IfNotPresent
    name: rke-ingress-controller-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/config
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: rke-job-deployer-token-8j7wv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: zx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: rke-job-deployer
  serviceAccountName: rke-job-deployer
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: rke-ingress-controller
        path: rke-ingress-controller.yaml
      name: rke-ingress-controller
    name: config-volume
  - name: rke-job-deployer-token-8j7wv
    secret:
      defaultMode: 420
      secretName: rke-job-deployer-token-8j7wv
