apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-02T04:33:44Z"
  generateName: coredns-autoscaler-65bfc8d47d-
  labels:
    k8s-app: coredns-autoscaler
    pod-template-hash: 65bfc8d47d
  name: coredns-autoscaler-65bfc8d47d-72mhs
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-autoscaler-65bfc8d47d
    uid: 0321f34e-1d3d-457a-8a4f-130a7252333c
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
  containers:
  - command:
    - /cluster-proportional-autoscaler
    - --namespace=kube-system
    - --configmap=coredns-autoscaler
    - --target=Deployment/coredns
    - --default-params={"linear":{"coresPerReplica":128,"nodesPerReplica":4,"min":1,"preventSinglePointFailure":true}}
    - --nodelabels=node-role.kubernetes.io/worker=true,beta.kubernetes.io/os=linux
    - --logtostderr=true
    - --v=2
    image: rancher/cluster-proportional-autoscaler:1.7.1
    imagePullPolicy: IfNotPresent
    name: autoscaler
    resources:
      requests:
        cpu: 20m
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: coredns-autoscaler-token-zcjxf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: zx
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns-autoscaler
  serviceAccountName: coredns-autoscaler
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  volumes:
  - name: coredns-autoscaler-token-zcjxf
    secret:
      defaultMode: 420
      secretName: coredns-autoscaler-token-zcjxf
