apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T04:33:07Z"
  name: service-account-controller
  namespace: kube-system
secrets:
- name: service-account-controller-token-6c7n2
