apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-02T04:33:11Z"
  name: clusterrole-aggregation-controller
  namespace: kube-system
secrets:
- name: clusterrole-aggregation-controller-token-9t4ml
