apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"kubernetes.io/name":"Metrics-server"},"name":"metrics-server","namespace":"kube-system"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":443}],"selector":{"k8s-app":"metrics-server"}}}
  creationTimestamp: "2020-04-02T04:33:48Z"
  labels:
    kubernetes.io/name: Metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  clusterIP: 10.43.222.137
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: metrics-server
  sessionAffinity: None
  type: ClusterIP
