apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-02T04:34:06Z"
  generateName: cattle-node-agent-
  labels:
    app: cattle-agent
    controller-revision-hash: 55cc8cf477
    pod-template-generation: "1"
  name: cattle-node-agent-rsjsp
  namespace: cattle-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: cattle-node-agent
    uid: d759252b-d731-4159-b72a-a92a71fb7ed7
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - zx
  containers:
  - env:
    - name: CATTLE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CATTLE_SERVER
      value: https://192.168.4.1:444
    - name: CATTLE_CA_CHECKSUM
      value: c54fa59dafbadb2890e635b8ad1c5529f84ea596c459568ceffbeba3543895e8
    - name: CATTLE_CLUSTER
      value: "false"
    - name: CATTLE_K8S_MANAGED
      value: "true"
    - name: CATTLE_AGENT_CONNECT
      value: "true"
    image: rancher/rancher-agent:v2.4.2
    imagePullPolicy: IfNotPresent
    name: agent
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cattle-credentials
      name: cattle-credentials
      readOnly: true
    - mountPath: /etc/kubernetes
      name: k8s-ssl
    - mountPath: /var/run
      name: var-run
    - mountPath: /run
      name: run
    - mountPath: /etc/docker/certs.d
      name: docker-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: cattle-token-n9x59
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: zx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: cattle
  serviceAccountName: cattle
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: k8s-ssl
  - hostPath:
      path: /var/run
      type: DirectoryOrCreate
    name: var-run
  - hostPath:
      path: /run
      type: DirectoryOrCreate
    name: run
  - name: cattle-credentials
    secret:
      defaultMode: 320
      secretName: cattle-credentials-8e27dab
  - hostPath:
      path: /etc/docker/certs.d
      type: DirectoryOrCreate
    name: docker-certs
  - name: cattle-token-n9x59
    secret:
      defaultMode: 420
      secretName: cattle-token-n9x59
