apiVersion: v1
data:
  namespace: Yy1rOXJ6eA==
  token: NnF0cDVtOTJkZ2p4eDR0MjJyaG02bnRqcGs1Mmg1d3dzdGNrOGN2YnBqNmJncm0ybWw4ajVt
  url: aHR0cHM6Ly8xOTIuMTY4LjQuMTo0NDQ=
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: c-k9rzx:p-b5wsr
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"namespace":"Yy1rOXJ6eA==","token":"NnF0cDVtOTJkZ2p4eDR0MjJyaG02bnRqcGs1Mmg1d3dzdGNrOGN2YnBqNmJncm0ybWw4ajVt","url":"aHR0cHM6Ly8xOTIuMTY4LjQuMTo0NDQ="},"kind":"Secret","metadata":{"annotations":{},"name":"cattle-credentials-8e27dab","namespace":"cattle-system"},"type":"Opaque"}
  creationTimestamp: "2020-04-02T04:34:05Z"
  name: cattle-credentials-8e27dab
  namespace: cattle-system
type: Opaque
