apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"cattle","namespace":"cattle-system"}}
  creationTimestamp: "2020-04-02T04:34:05Z"
  name: cattle
  namespace: cattle-system
secrets:
- name: cattle-token-n9x59
