apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2020-04-03T01:39:28Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: katafygio
    chart: katafygio-1.0.0
    heritage: Tiller
    io.cattle.field/appId: katafygio
    release: katafygio
  name: katafygio
  namespace: katafygio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
