apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-03T01:39:28Z"
  labels:
    app: katafygio
    chart: katafygio-1.0.0
    heritage: Tiller
    io.cattle.field/appId: katafygio
    release: katafygio
  name: katafygio
  namespace: katafygio
secrets:
- name: katafygio-token-zm5lj
