apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.4.1"],"port":31000,"protocol":"TCP","serviceName":"kafka:kafka-cp-control-center","allNodes":true}]'
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-control-center
    chart: cp-control-center-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-control-center
  namespace: kafka
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-control-center
      release: kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-04-03T01:06:10Z"
        field.cattle.io/ports: '[[{"containerPort":9021,"dnsName":"kafka-cp-control-center","kind":"ClusterIP","name":"cc-http","protocol":"TCP"}]]'
        field.cattle.io/publicEndpoints: '[{"addresses":["192.168.4.1"],"allNodes":true,"port":31000,"protocol":"TCP","serviceId":"kafka:kafka-cp-control-center"}]'
        prometheus.io/port: "5556"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: cp-control-center
        release: kafka
    spec:
      containers:
      - env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-cp-kafka-headless:9092
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: http://kafka-cp-kafka-connect:8083
        - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
          value: http://kafka-cp-ksql-server:8088
        - name: CONTROL_CENTER_KSQL_URL
          value: http://kafka-cp-ksql-server:8088
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "3"
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: http://kafka-cp-schema-registry:8081
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
        - name: KAFKA_HEAP_OPTS
          value: -Xms512M -Xmx512M
        image: confluentinc/cp-enterprise-control-center:latest
        imagePullPolicy: IfNotPresent
        name: cp-control-center
        ports:
        - containerPort: 9021
          name: cc-http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
