apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-ksql-server
    chart: cp-ksql-server-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-ksql-server
  namespace: kafka
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-ksql-server
      release: kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-04-03T00:52:56Z"
        field.cattle.io/ports: '[[{"containerPort":5556,"dnsName":"kafka-cp-ksql-server","hostPort":0,"kind":"ClusterIP","name":"5556tcp02","protocol":"TCP","sourcePort":0}],[{"containerPort":8088,"dnsName":"kafka-cp-ksql-server","hostPort":0,"kind":"ClusterIP","name":"server","protocol":"TCP","sourcePort":0},{"containerPort":5555,"dnsName":"kafka-cp-ksql-server","hostPort":0,"kind":"ClusterIP","name":"jmx","protocol":"TCP","sourcePort":0}]]'
        prometheus.io/port: "5556"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: cp-ksql-server
        release: kafka
    spec:
      containers:
      - command:
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:MaxRAMFraction=1
        - -XshowSettings:vm
        - -jar
        - jmx_prometheus_httpserver.jar
        - "5556"
        - /etc/jmx-ksql-server/jmx-ksql-server-prometheus.yml
        image: solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
        imagePullPolicy: IfNotPresent
        name: prometheus-jmx-exporter
        ports:
        - containerPort: 5556
          name: 5556tcp02
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/jmx-ksql-server
          name: jmx-config
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafka-cp-kafka-headless:9092
        - name: KSQL_HEAP_OPTS
          value: -Xms512M -Xmx512M
        - name: KSQL_JMX_PORT
          value: "5555"
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: http://kafka-cp-schema-registry:8081
        - name: KSQL_KSQL_SERVICE_ID
          value: kafka
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        image: confluentinc/ksqldb-server:latest
        imagePullPolicy: IfNotPresent
        name: cp-ksql-server
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP
        - containerPort: 5555
          name: jmx
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-cp-ksql-server-jmx-configmap
        name: jmx-config
