apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2020-04-03T00:50:55Z"
    field.cattle.io/ports: '[[{"containerPort":5556,"dnsName":"kafka-cp-schema-registry","hostPort":0,"kind":"ClusterIP","name":"5556tcp02","protocol":"TCP","sourcePort":0}],[{"containerPort":8081,"dnsName":"kafka-cp-schema-registry","hostPort":0,"kind":"ClusterIP","name":"schema-registry","protocol":"TCP","sourcePort":0},{"containerPort":5555,"dnsName":"kafka-cp-schema-registry","hostPort":0,"kind":"ClusterIP","name":"jmx","protocol":"TCP","sourcePort":0}]]'
    prometheus.io/port: "5556"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-04-03T00:50:56Z"
  generateName: kafka-cp-schema-registry-8684dfb5f-
  labels:
    app: cp-schema-registry
    pod-template-hash: 8684dfb5f
    release: kafka
  name: kafka-cp-schema-registry-8684dfb5f-5vltf
  namespace: kafka
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kafka-cp-schema-registry-8684dfb5f
    uid: 5ead303d-39ef-4bbb-afd3-7d9bc1eeb15e
spec:
  containers:
  - command:
    - java
    - -XX:+UnlockExperimentalVMOptions
    - -XX:+UseCGroupMemoryLimitForHeap
    - -XX:MaxRAMFraction=1
    - -XshowSettings:vm
    - -jar
    - jmx_prometheus_httpserver.jar
    - "5556"
    - /etc/jmx-schema-registry/jmx-schema-registry-prometheus.yml
    image: solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    imagePullPolicy: IfNotPresent
    name: prometheus-jmx-exporter
    ports:
    - containerPort: 5556
      name: 5556tcp02
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/jmx-schema-registry
      name: jmx-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z6dxk
      readOnly: true
  - env:
    - name: JMX_PORT
      value: "5555"
    - name: SCHEMA_REGISTRY_HEAP_OPTS
      value: -Xms512M -Xmx512M
    - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
      value: PLAINTEXT://kafka-cp-kafka-headless:9092
    - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
      value: kafka
    - name: SCHEMA_REGISTRY_LISTENERS
      value: http://0.0.0.0:8081
    - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
      value: "true"
    - name: SCHEMA_REGISTRY_HOST_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: confluentinc/cp-schema-registry:latest
    imagePullPolicy: IfNotPresent
    name: cp-schema-registry-server
    ports:
    - containerPort: 8081
      name: schema-registry
      protocol: TCP
    - containerPort: 5555
      name: jmx
      protocol: TCP
    resources: {}
    securityContext:
      capabilities: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z6dxk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: zx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: kafka-cp-schema-registry-jmx-configmap
    name: jmx-config
  - name: default-token-z6dxk
    secret:
      defaultMode: 420
      secretName: default-token-z6dxk
