apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-zookeeper
    chart: cp-zookeeper-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-zookeeper
  namespace: kafka
spec:
  clusterIP: 10.43.144.49
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: cp-zookeeper
    release: kafka
  sessionAffinity: None
  type: ClusterIP
