apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-kafka-connect
    chart: cp-kafka-connect-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-kafka-connect
  namespace: kafka
spec:
  clusterIP: 10.43.171.102
  ports:
  - name: kafka-connect
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: cp-kafka-connect
    release: kafka
  sessionAffinity: None
  type: ClusterIP
