apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-kafka-rest
    chart: cp-kafka-rest-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-kafka-rest
  namespace: kafka
spec:
  clusterIP: 10.43.168.213
  ports:
  - name: rest-proxy
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: cp-kafka-rest
    release: kafka
  sessionAffinity: None
  type: ClusterIP
