apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-schema-registry
    chart: cp-schema-registry-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-schema-registry
  namespace: kafka
spec:
  clusterIP: 10.43.112.63
  ports:
  - name: schema-registry
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cp-schema-registry
    release: kafka
  sessionAffinity: None
  type: ClusterIP
