apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T00:47:25Z"
  labels:
    app: cp-kafka
    chart: cp-kafka-0.1.0
    heritage: Tiller
    io.cattle.field/appId: kafka
    release: kafka
  name: kafka-cp-kafka-headless
  namespace: kafka
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: cp-kafka
    release: kafka
  sessionAffinity: None
  type: ClusterIP
