apiVersion: v1
data:
  config.json: '{"1.1.1":"Clusters provisioned by RKE doesn''t require or maintain
    a configuration file for kube-apiserver.\nAll configuration is passed in as arguments
    at container run time.","1.1.13":"Clusters provisioned by RKE does not store the
    kubernetes default kubeconfig credentials file on the nodes.","1.1.14":"Clusters
    provisioned by RKE does not store the kubernetes default kubeconfig credentials
    file on the nodes.","1.1.15":"Clusters provisioned by RKE doesn''t require or
    maintain a configuration file for scheduler.\nAll configuration is passed in as
    arguments at container run time.","1.1.16":"Clusters provisioned by RKE doesn''t
    require or maintain a configuration file for scheduler.\nAll configuration is
    passed in as arguments at container run time.","1.1.17":"Clusters provisioned
    by RKE doesn''t require or maintain a configuration file for controller-manager.\nAll
    configuration is passed in as arguments at container run time.","1.1.18":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for controller-manager.\nAll
    configuration is passed in as arguments at container run time.","1.1.2":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for kube-apiserver.\nAll
    configuration is passed in as arguments at container run time.","1.1.3":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for controller-manager.\nAll
    configuration is passed in as arguments at container run time.","1.1.4":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for controller-manager.\nAll
    configuration is passed in as arguments at container run time.","1.1.5":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for scheduler.\nAll
    configuration is passed in as arguments at container run time.","1.1.6":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for scheduler.\nAll
    configuration is passed in as arguments at container run time.","1.1.7":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for etcd.\nAll
    configuration is passed in as arguments at container run time.","1.1.8":"Clusters
    provisioned by RKE doesn''t require or maintain a configuration file for etcd.\nAll
    configuration is passed in as arguments at container run time.","1.3.6":"Clusters
    provisioned by RKE handles certificate rotation directly through RKE.","4.1.1":"Clusters
    provisioned by RKE doesn’t require or maintain a configuration file for the kubelet
    service.\nAll configuration is passed in as arguments at container run time.","4.1.10":"Clusters
    provisioned by RKE doesn’t require or maintain a configuration file for the kubelet.\nAll
    configuration is passed in as arguments at container run time.","4.1.2":"Clusters
    provisioned by RKE doesn’t require or maintain a configuration file for the kubelet
    service.\nAll configuration is passed in as arguments at container run time.","4.1.9":"Clusters
    provisioned by RKE doesn’t require or maintain a configuration file for the kubelet.\nAll
    configuration is passed in as arguments at container run time.","4.2.12":"Clusters
    provisioned by RKE handles certificate rotation directly through RKE."}'
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T04:34:05Z"
  labels:
    cattle.io/creator: norman
  name: na-rke-cis-1.5
  namespace: security-scan
