apiVersion: v1
data:
  config.json: '{"1.1.12":"A system service account is required for etcd data directory
    ownership. Refer to Rancher''s hardening guide for more details on how to configure
    this ownership.","1.2.16":"Enabling Pod Security Policy can cause applications
    to unexpectedly fail.","1.2.33":"Enabling encryption changes how data can be recovered
    as data is encrypted.","1.2.34":"Enabling encryption changes how data can be recovered
    as data is encrypted.","1.2.6":"When generating serving certificates, functionality
    could break in conjunction with hostname overrides which are required for certain
    cloud providers.","4.2.10":"When generating serving certificates, functionality
    could break in conjunction with hostname overrides which are required for certain
    cloud providers.","4.2.6":"System level configurations are required prior to provisioning
    the cluster in order for this argument to be set to true.","5.1.5":"Kubernetes
    provides default service accounts to be used.","5.2.2":"Enabling Pod Security
    Policy can cause applications to unexpectedly fail.","5.2.3":"Enabling Pod Security
    Policy can cause applications to unexpectedly fail.","5.2.4":"Enabling Pod Security
    Policy can cause applications to unexpectedly fail.","5.2.5":"Enabling Pod Security
    Policy can cause applications to unexpectedly fail.","5.3.2":"Enabling Network
    Policies can prevent certain applications from communicating with each other.","5.6.4":"Kubernetes
    provides a default namespace."}'
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-02T04:34:05Z"
  labels:
    cattle.io/creator: norman
  name: ds-rke-cis-1.5
  namespace: security-scan
